name: flutter_chat_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.2
  contacts_service: ^0.3.10
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.0+1
  intl: ^0.16.1
  firebase_auth: ^0.16.0
  path_provider: ^1.6.7
  provider: ^4.0.5+1
  permission_handler: ^5.0.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.1+2
  image_picker: ^0.6.0+17
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_database: ^3.0.7
  firebase_storage: ^3.1.6
  fluttertoast: ^4.0.0
  cached_network_image: 2.2.0+1
  firebase_messaging: 6.0.13
  flutter_local_notifications: 1.4.0
  photo_view: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - data/