name: flutter_chat_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    # for multi language
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  # for network connection
  connectivity: ^0.4.2
  # for contacts
  contacts_service: ^0.3.10
  # for ios icons
  cupertino_icons: ^0.1.3
  # for provider
  provider: ^4.0.5+1
  # for permissions
  permission_handler: ^5.0.0
  # for api call
  http: ^0.12.0+2
  # for shared pref
  shared_preferences: ^0.5.1+2
  # for image pic from camera and gallery
  image_picker: ^0.6.0+17
  # for firebase
  cloud_firestore: ^0.13.0+1
  intl: ^0.16.1
  firebase_auth: ^0.16.0
  path_provider: ^1.6.7
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_database: ^3.0.7
  firebase_storage: ^3.1.6
  firebase_messaging: 6.0.13
  # for toast
  fluttertoast: ^4.0.0
  # for network images
  cached_network_image: 2.2.0+1
  # for notifications
  flutter_local_notifications: 1.4.0
  # for photo full view
  photo_view: ^0.5.0
  # for location
  location: ^2.3.5
  geolocator: ^5.3.2+2
  # for fingerprint auth
  local_auth: 0.6.2+3
  # for amazon cognito auth
  amazon_cognito_identity_dart: "^0.0.19"
  flutter_splash: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - data/